on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - uses: keyskull/gh-action-get-changed-files@master
      with:
        token: ${{ secrets.SYNCED_GITHUB_TOKEN }}
              
    - name: Files Sync Action
      uses: kbrashears5/github-action-file-sync@v2.0.0
      with:
        REPOSITORIES: |
          keyskull/publish:metadata
        FILES: |
          ~/metadata.json=metadata.json
        TOKEN: ${{secrets.SYNCED_GITHUB_TOKEN}}
        
    - name: Copy json files
      run: |
        mkdir ./metadata
        cp ~/metadata.json ./metadata
        mv ~/files_detail.json  ./publish
        mv ~/metadata.json  ./publish

    - name: Store Metadata
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.SYNCED_GITHUB_TOKEN}}
        publish_dir: ./metadata
        publish_branch: metadata
        
    - name: Publish to gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.SYNCED_GITHUB_TOKEN}}
        publish_dir: ./publish
        


  
