on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - uses: keyskull/gh-action-get-changed-files@master
      with:
        token: ${{ secrets.SYNCED_GITHUB_TOKEN }}
        
    - name: Copy json file
      run: mv ~/files_detail.json ./publish
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.SYNCED_GITHUB_TOKEN}}
        publish_dir: ./publish
        


  
